// Messages that come from the backend as a stable key plus parameters (pygmalion_hoard/messages.py): errors with their hints, warnings, plan lines,
// notes, progress messages and job titles. The API keeps an English sentence for assistants; the UI formats these keys itself.
// Each entry is [español, English]; `{name}` placeholders take the parameters. tests/test_client.py checks that every backend key is here, in both
// languages and with the same placeholders. Keys: err_<key> (an error), hint_<key> (what to do about it), msg_<key> (any other sentence).
export const MESSAGES = {
  // ---- settings
  err_not_gpu_index: ["«{part}» no es un índice de GPU.", "'{part}' is not a GPU index."],
  err_setting_unknown: ["El ajuste {key} no existe.", "Unknown setting {key}."],
  hint_setting_unknown: ["Los que existen: {options}.", "Known: {options}."],
  err_setting_choice: ["{key} debe ser uno de estos valores: {options}.", "{key} must be one of {options}."],
  err_setting_bool: ["{key} debe estar activado o desactivado.", "{key} must be on or off."],
  err_setting_number: ["{key} debe ser un número.", "{key} must be a number."],
  err_setting_range: ["{key} debe estar entre {low} y {high}.", "{key} must be between {low} and {high}."],
  err_gpu_reserved: ["La GPU {gpus} es del propietario de este ordenador.", "GPU {gpus} belongs to the owner of this computer."],
  hint_gpu_reserved: ["Repite la llamada con confirm_reserved=true solo si el propietario lo permite expresamente.", "Repeat the call with confirm_reserved=true only if the owner explicitly allows it."],
  err_no_gpu_allowed_setting: ["Hay que permitir al menos una GPU.", "At least one GPU must be allowed."],
  hint_no_gpu_allowed_setting: ["Indica en gpus.allowed, por ejemplo, 2,3.", "Set gpus.allowed to e.g. 2,3."],
  // ---- store
  err_dataset_exists: ["Ya existe un dataset llamado «{name}».", "A dataset called '{name}' already exists."],
  hint_dataset_exists: ["Elige otro nombre o añádele una versión.", "Pick another name or add a version to it."],
  err_no_dataset: ["No existe el dataset {ref}.", "No dataset {ref}."],
  hint_no_dataset: ["Consulta los datasets en la página Datasets.", "List datasets with datasets_list."],
  err_no_dataset_version: ["No existe la versión de dataset {ref}.", "No dataset version {ref}."],
  hint_no_dataset_version: ["Las versiones se ven al abrir el dataset.", "Dataset versions are listed by dataset_get."],
  err_dataset_no_version: ["El dataset {name} no tiene la versión {n}.", "Dataset {name} has no version {n}."],
  err_dataset_no_versions: ["El dataset {name} aún no tiene versiones.", "Dataset {name} has no versions yet."],
  err_artifact_kind_unknown: ["Tipo de artefacto desconocido: {kind}.", "Unknown artifact kind {kind}."],
  hint_artifact_kind_unknown: ["Tipos: {options}.", "Kinds: {options}."],
  err_no_artifact: ["No existe el artefacto {ref}.", "No artifact {ref}."],
  hint_no_artifact: ["Consulta los artefactos en Linaje.", "List artifacts with artifacts_list."],
  err_no_job: ["No existe el trabajo {id}.", "No job {id}."],
  hint_no_job: ["Consulta los trabajos en la página Trabajos.", "List jobs with jobs_list."],
  // ---- jobs
  err_env_not_set: ["El entorno de entrenamiento no está configurado.", "The trainer environment is not set up."],
  hint_env_not_set: ["Indica env.python en Ajustes (la comprobación del entorno explica los pasos).", "Set env.python in Settings (run env_check for the steps)."],
  err_worker_missing: ["Falta el proceso de trabajo {name}: {script}.", "The worker {name} is missing: {script}."],
  hint_worker_missing: ["Reinstala la aplicación.", "Reinstall the app."],
  err_worker_exit: ["{name} terminó con el código {code}: {tail}", "{name} exited with code {code}: {tail}"],
  err_pipeline_ref_missing: ["El paso de la cadena necesita ${name}, que ningún paso anterior ha producido.", "The pipeline step needs ${name}, which no earlier step produced."],
  hint_pipeline_ref_missing: ["Disponibles: {options}.", "Available: {options}."],
  err_pipeline_ref_none: ["El paso de la cadena necesita ${name}, que ningún paso anterior ha producido.", "The pipeline step needs ${name}, which no earlier step produced."],
  hint_pipeline_ref_none: ["Ningún paso anterior ha producido nada todavía.", "No earlier step has produced anything yet."],
  err_job_kind_unknown: ["Tipo de trabajo desconocido: «{kind}».", "Unknown job kind '{kind}'."],
  hint_job_kind_unknown: ["Tipos: {options}.", "Kinds: {options}."],
  err_job_kind_unknown_step: ["Tipo de trabajo desconocido en la cadena: «{kind}».", "Unknown job kind '{kind}' in the pipeline."],
  hint_job_kind_unknown_step: ["Tipos: {options}.", "Kinds: {options}."],
  err_pipeline_empty: ["Una cadena necesita al menos un paso.", "A pipeline needs at least one step."],
  err_job_not_cancellable: ["El trabajo {id} está en estado «{state}»: no hay nada que cancelar.", "Job {id} is {state}: nothing to cancel."],
  err_job_not_resumable: ["El trabajo {id} está en estado «{state}»: solo se reanudan los interrumpidos, fallidos o cancelados.", "Job {id} is {state}: only interrupted, failed or cancelled jobs resume."],
  err_job_still_active: ["El trabajo {id} está en estado «{state}»: cancélalo antes.", "Job {id} is {state}: cancel it first."],
  err_job_no_runner: ["No hay ejecutor para «{kind}».", "No runner for {kind}."],
  err_cancelled: ["Cancelado.", "Cancelled."],
  err_job_crashed: ["Error inesperado: {detail}", "Unexpected error: {detail}"],
  hint_job_crashed: ["Consulta el registro del trabajo.", "See the job log."],
  // ---- ops
  err_repo_no_safetensors: ["{repo} no tiene pesos .safetensors.", "{repo} has no .safetensors weights."],
  hint_repo_no_safetensors: ["Solo se pueden entrenar o convertir modelos en safetensors.", "Only safetensors checkpoints can be trained or converted."],
  err_repo_too_big: ["{repo} necesita {need_gb} GB y solo hay {free_gb} GB libres.", "{repo} needs {need_gb} GB and only {free_gb} GB are free."],
  hint_repo_too_big: ["Libera espacio o cambia paths.work en Ajustes.", "Free space or change paths.work."],
  err_train_no_fit: ["{reason}", "{reason}"],
  hint_train_no_fit: ["Baja seq_len o el lote, usa QLoRA, o fuerza el trabajo para ponerlo en cola igualmente.", "Lower seq_len or batch, use QLoRA, or pass force=true to queue it anyway."],
  err_models_unreadable: ["{detail}", "{detail}"],
  hint_models_unreadable: ["Cada modelo necesita archivos .safetensors.", "Each model needs .safetensors files."],
  err_models_incompatible: ["Los modelos no son compatibles: {problems}", "The models are not compatible: {problems}"],
  hint_models_incompatible: ["Solo se pueden fusionar modelos con la misma arquitectura y los mismos tamaños.", "Only models with the same architecture and sizes can be merged."],
  err_ctx_factor_needed: ["Indica un factor mayor que 1 (2, 4 u 8) o una longitud objetivo mayor que la del propio modelo.", "Give a factor above 1 (2, 4 or 8) or a target length above the model's own."],
  hint_ctx_factor_needed: ["El contexto del modelo es de {original} tokens.", "The model's context is {original} tokens."],
  err_ctx_factor_needed_unknown: ["Indica un factor mayor que 1 (2, 4 u 8) o una longitud objetivo mayor que la del propio modelo.", "Give a factor above 1 (2, 4 or 8) or a target length above the model's own."],
  hint_ctx_factor_needed_unknown: ["Se desconoce el contexto del modelo.", "The model's context is unknown."],
  err_quantize_needs_source: ["Indica un GGUF (un artefacto GGUF) o un modelo (una carpeta de Hugging Face que se convertirá antes).", "Give gguf (a GGUF artifact) or model (a Hugging Face folder to convert first)."],
  err_config_unreadable: ["{path}: falta config.json o no se puede leer.", "{path}: config.json is missing or unreadable."],
  hint_config_unreadable: ["Elige una carpeta de modelo de Hugging Face.", "Pick a Hugging Face model folder."],
  // ---- gpus
  err_gpu_no_fit: ["{reason}", "{reason}"],
  hint_gpu_no_fit: ["Usa un modelo más pequeño, una secuencia más corta o QLoRA, o permite más GPU en Ajustes.", "Use a smaller model, a shorter sequence, QLoRA, or allow more GPUs in Settings."],
  err_no_gpu_allowed: ["No hay ninguna GPU permitida.", "No GPU is allowed."],
  hint_no_gpu_allowed: ["Indica gpus.allowed en Ajustes.", "Set gpus.allowed in Settings."],
  err_gpu_index_not_allowed: ["La GPU {index} no está en la lista de permitidas.", "GPU {index} is not in the allowed list."],
  hint_gpu_index_not_allowed: ["Las GPU permitidas se eligen en Ajustes.", "Allowed GPUs are set in Settings."],
  err_gpu_hub_placed: ["El hub colocó el trabajo en la GPU {gpu}, que no está permitida.", "The hub placed the job on GPU {gpu}, which is not allowed."],
  err_cancelled_waiting_gpu: ["Cancelado mientras esperaba una GPU.", "Cancelled while waiting for a GPU."],
  err_gpu_lease_failed: ["Falló la reserva de la GPU: {detail}", "The GPU lease failed: {detail}"],
  hint_gpu_lease_failed: ["Comprueba el hub de la familia (Hoard Hub) y la memoria de la GPU.", "Check the family hub (Hoard Hub) and the GPU memory."],
  // ---- planner
  err_plan_no_config: ["{name}: config.json no indica el tamaño oculto ni las capas, así que no se puede estimar la memoria.", "{name}: config.json has no hidden size or layers, so memory cannot be estimated."],
  hint_plan_no_config: ["Elige una carpeta de modelo decodificador de Hugging Face.", "Pick a Hugging Face decoder model folder."],
  err_train_method_invalid: ["El método debe ser qlora o lora.", "method must be qlora or lora."],
  // ---- publish
  err_ollama_tag_invalid: ["«{tag}» no es una etiqueta válida de Ollama.", "'{tag}' is not a valid Ollama tag."],
  hint_ollama_tag_invalid: ["Usa letras, dígitos, puntos y guiones.", "Use letters, digits, dots and hyphens."],
  err_modelfile_parameter: ["Parámetro no válido del Modelfile: «{key}».", "Invalid Modelfile parameter '{key}'."],
  err_gguf_file_missing: ["Falta el archivo de {name}: {path}.", "The file of {name} is missing: {path}."],
  hint_gguf_file_missing: ["Vuelve a generarlo o elige otro GGUF.", "Rebuild it or pick another GGUF."],
  err_ollama_missing: ["No se ha encontrado Ollama.", "Ollama was not found."],
  hint_ollama_missing: ["Instala Ollama o indica publish.ollama_exe en Ajustes.", "Install Ollama or set publish.ollama_exe in Settings."],
  err_ollama_create_failed: ["Falló ollama create: {detail}", "ollama create failed: {detail}"],
  hint_ollama_create_failed: ["Comprueba que el servicio de Ollama está en marcha.", "Check that the Ollama service is running."],
  err_no_free_port: ["No hay ningún puerto libre para el servidor de llama.cpp.", "No free port for the llama.cpp server."],
  hint_no_free_port: ["Sube publish.llama_port_start en Ajustes.", "Raise publish.llama_port_start in Settings."],
  err_llama_server_missing: ["No se ha encontrado llama-server.", "llama-server was not found."],
  hint_llama_server_missing: ["Indica llama.bin_dir en Ajustes.", "Set llama.bin_dir in Settings."],
  err_gpu_not_in_allowed: ["La GPU {gpu} no está en la lista de permitidas ({allowed}).", "GPU {gpu} is not in the allowed list {allowed}."],
  hint_gpu_not_in_allowed: ["Cambia gpus.allowed en Ajustes si el propietario está de acuerdo.", "Change gpus.allowed in Settings if the owner agrees."],
  err_backend_id_invalid: ["«{id}» no es un identificador de servicio válido.", "'{id}' is not a valid backend id."],
  err_backends_refused: ["backends.json rechazó la entrada: {detail}", "backends.json refused the entry: {detail}"],
  err_not_published: ["{name} no está publicado.", "{name} is not published."],
  hint_not_published: ["No hay nada que retirar.", "Nothing to remove."],
  err_only_pyg_tags: ["Solo se retiran las etiquetas creadas por Pygmalion (pyg-...).", "Only tags created by Pygmalion (pyg-...) are removed."],
  err_ollama_rm_failed: ["Falló ollama rm: {detail}", "ollama rm failed: {detail}"],
  hint_ollama_rm_failed: ["Comprueba que el servicio de Ollama está en marcha.", "Check that the Ollama service is running."],
  err_unpublish_nothing: ["Nada coincide con lo que pedías retirar.", "Nothing matched what you asked to remove."],
  hint_unpublish_nothing: ["Publicaciones existentes: {entries}.", "Published entries: {entries}."],
  // ---- runners
  err_disk_low: ["No hay espacio libre en disco para {what}: hacen falta unos {need_gb} GB y hay {free_gb} GB libres.", "Not enough free disk space for {what}: need about {need_gb} GB, {free_gb} GB free."],
  hint_disk_low: ["Libera espacio en la carpeta de trabajo o cambia paths.work en Ajustes.", "Free space in the work folder or change paths.work in Settings."],
  err_tool_not_found: ["No se ha encontrado {name}.", "{name} was not found."],
  hint_tool_not_found: ["Indica {setting} en Ajustes (la comprobación del entorno lista lo que falta).", "Set {setting} in Settings (env_check lists what is missing)."],
  err_model_folder_missing: ["Falta la carpeta del modelo de {name}: {path}.", "The model folder of {name} is missing: {path}."],
  hint_model_folder_missing: ["Descárgalo o vuelve a generarlo.", "Download or rebuild it."],
  err_dataset_no_train: ["La versión del dataset no tiene registros de entrenamiento.", "The dataset version has no training records."],
  hint_dataset_no_train: ["Revísala: acepta algunos registros o vuelve a construirla con más material.", "Review it: accept some records or rebuild with more material."],
  err_convert_unsupported: ["{note}", "{note}"],
  hint_convert_unsupported: ["Actualiza las fuentes de llama.cpp (llama.src_dir) o elige otro modelo.", "Update the llama.cpp sources (llama.src_dir) or pick another model."],
  err_convert_failed: ["Falló la conversión a GGUF: {detail}", "The GGUF conversion failed: {detail}"],
  hint_convert_failed: ["Lee el registro del trabajo; una arquitectura no admitida necesita un llama.cpp más reciente.", "Read the job log; an unsupported architecture needs a newer llama.cpp."],
  err_convert_failed_code: ["Falló la conversión a GGUF: código de salida {code}", "The GGUF conversion failed: exit code {code}"],
  hint_convert_failed_code: ["Lee el registro del trabajo; una arquitectura no admitida necesita un llama.cpp más reciente.", "Read the job log; an unsupported architecture needs a newer llama.cpp."],
  err_imatrix_failed: ["Falló llama-imatrix: {detail}", "llama-imatrix failed: {detail}"],
  hint_imatrix_failed: ["Si se quedó sin memoria, libera la GPU o usa un modelo más pequeño.", "If it ran out of memory, free the GPU or use a smaller model."],
  err_imatrix_failed_code: ["Falló llama-imatrix: código de salida {code}", "llama-imatrix failed: exit code {code}"],
  hint_imatrix_failed_code: ["Si se quedó sin memoria, libera la GPU o usa un modelo más pequeño.", "If it ran out of memory, free the GPU or use a smaller model."],
  err_quantize_failed: ["Falló llama-quantize: {detail}", "llama-quantize failed: {detail}"],
  hint_quantize_failed: ["Lee el registro del trabajo.", "Read the job log."],
  err_quantize_failed_code: ["Falló llama-quantize: código de salida {code}", "llama-quantize failed: exit code {code}"],
  hint_quantize_failed_code: ["Lee el registro del trabajo.", "Read the job log."],
  err_perplexity_failed: ["llama-perplexity no dio ningún resultado: {detail}", "llama-perplexity gave no result: {detail}"],
  hint_perplexity_failed: ["Lee el registro del trabajo.", "Read the job log."],
  err_perplexity_failed_code: ["llama-perplexity no dio ningún resultado: código de salida {code}", "llama-perplexity gave no result: exit code {code}"],
  hint_perplexity_failed_code: ["Lee el registro del trabajo.", "Read the job log."],
  // ---- evaluate
  err_intent_unknown: ["Intención desconocida: «{intent}».", "Unknown intent '{intent}'."],
  hint_intent_unknown: ["Usa una de estas: {options}, o indica las suites.", "Use one of: {options} or pass suites."],
  err_evaluate_kind: ["{name} es de tipo «{kind}»: solo se pueden evaluar archivos GGUF y etiquetas de Ollama.", "{name} is a {kind}: only GGUF files and Ollama tags can be evaluated."],
  hint_evaluate_kind: ["Conviértelo antes a GGUF.", "Convert it to GGUF first (convert_start)."],
  err_galton_refused: ["Galton rechazó {tool}: {detail}", "Galton refused {tool}: {detail}"],
  hint_galton_refused: ["Comprueba las suites y los modelos.", "Check the suites and contestants."],
  err_galton_offline: ["Modo sin red: no se puede contactar con Galton.", "Offline mode: Galton cannot be reached."],
  err_galton_token_missing: ["No se ha encontrado el token de Galton.", "Galton's token was not found."],
  hint_galton_token_missing: ["Indica en Ajustes galton.token_file con el archivo data/mcp-token de Galton.", "Set galton.token_file in Settings to Galton's data/mcp-token."],
  err_galton_unreachable: ["No se puede contactar con Galton's Hoard: {detail}.", "Cannot reach Galton's Hoard: {detail}."],
  hint_galton_unreachable: ["Arranca Galton's Hoard o el hub de la familia.", "Start Galton's Hoard or the family hub."],
  err_galton_status: ["Galton respondió {status}: {detail}", "Galton answered {status}: {detail}"],
  hint_galton_status: ["Comprueba los argumentos y el token de Galton.", "Check the arguments and Galton's token."],
  err_no_comparable: ["{name} no tiene ningún antecesor GGUF o de Ollama con el que compararse.", "{name} has no GGUF or Ollama ancestor to compare with."],
  hint_no_comparable: ["Indica con «comparar con» el GGUF o la etiqueta de Ollama del modelo padre.", "Pass against= with the GGUF or Ollama tag of the parent model."],
  err_galton_no_run: ["Galton no inició ninguna ejecución (su respuesta no trae identificador).", "Galton started no run (no run id in its answer)."],
  hint_galton_no_run: ["Respuesta: {answer}", "Answer: {answer}"],
  err_galton_run_ended: ["La ejecución {run} de Galton terminó como «{state}»: {detail}", "Galton's run {run} ended as {state}: {detail}"],
  hint_galton_run_ended: ["Abre la ejecución en Galton's Hoard.", "Open the run in Galton's Hoard."],
  err_galton_run_timeout: ["La ejecución {run} de Galton no terminó a tiempo.", "Galton's run {run} did not finish in time."],
  hint_galton_run_timeout: ["Sube galton.timeout_s o revisa la ejecución en Galton's Hoard.", "Raise galton.timeout_s or check the run in Galton's Hoard."],
  err_galton_run_models: ["La ejecución {run} de Galton lista {n} modelos en lugar de 2.", "Galton's run {run} lists {n} models instead of 2."],
  hint_galton_run_models: ["Abre la ejecución en Galton's Hoard.", "Open the run in Galton's Hoard."],
  err_galton_parent_failed: ["Galton no pudo ejecutar el modelo padre {name} en la ejecución {run}: {detail}", "Galton could not run the parent {name} in run {run}: {detail}"],
  hint_galton_parent_failed: ["Abre la ejecución en Galton's Hoard; libera una GPU o arregla el archivo y vuelve a evaluar.", "Open the run in Galton's Hoard; free a GPU or fix the file and evaluate again."],
  err_galton_child_failed: ["Galton no pudo ejecutar el modelo hijo {name} en la ejecución {run}: {detail}", "Galton could not run the child {name} in run {run}: {detail}"],
  hint_galton_child_failed: ["Abre la ejecución en Galton's Hoard; libera una GPU o arregla el archivo y vuelve a evaluar.", "Open the run in Galton's Hoard; free a GPU or fix the file and evaluate again."],
  err_ppl_not_stored: ["Se midió la perplejidad de {name}, pero no se pudo guardar en el artefacto.", "The perplexity of {name} was measured but could not be saved on the artifact."],
  hint_ppl_not_stored: ["Reanuda el trabajo para medirla otra vez.", "Resume the job to measure it again."],
  err_galton_judge_missing: ["Galton no tiene modelo juez, y los registros reservados los califica uno.", "Galton has no judge model, and the held-out records are graded by one."],
  hint_galton_judge_missing: ["Elige un modelo juez en los ajustes de Galton's Hoard (judge.contestant) y vuelve a evaluar.", "Choose a judge model in Galton's Hoard settings (judge.contestant) and evaluate again."],
  err_galton_judge_unavailable: ["El modelo juez de Galton no pudo calificar las respuestas de la ejecución {run} (quedan {n} sin calificar).", "Galton's judge model could not grade the answers of run {run} ({n} still wait)."],
  hint_galton_judge_unavailable: ["Revisa el modelo juez en Galton's Hoard (ajuste judge.contestant); cuando funcione, ejecuta judge_run allí y vuelve a evaluar.", "Check the judge model in Galton's Hoard (setting judge.contestant); once it works, run judge_run there and evaluate again."],
  err_galton_suite_empty: ["Galton no importó ningún caso en la suite {name}: {detail}", "Galton imported no case into the suite {name}: {detail}"],
  hint_galton_suite_empty: ["Abre la suite en Galton's Hoard.", "Open the suite in Galton's Hoard."],
  err_eval_no_records: ["{name} no viene de ninguna versión de dataset con registros reservados.", "{name} comes from no dataset version with held-out records."],
  err_eval_reference_missing: ["El modelo base {model} en {quant} no existe, así que no hay con qué comparar.", "The base model {model} at {quant} does not exist, so there is nothing to compare with."],
  hint_eval_reference_missing: ["Evalúa con «Evaluar» (prepara antes ese archivo) o indica con «comparar con» un archivo.", "Evaluate through evaluate_start, which prepares it first, or pass against= with a file to compare with."],
  hint_eval_no_records: ["Evalúa con otra intención (estilo, código, general...) o indica las suites.", "Evaluate with another intent (style, code, general...) or pass suites."],
  // ---- misc
  err_gguf_truncated: ["El archivo termina en mitad de la cabecera.", "The file ends in the middle of the header."],
  hint_gguf_truncated: ["El archivo no es un GGUF legible (v2 o v3).", "The file is not a readable GGUF (v2 or v3)."],
  err_gguf_string_long: ["Una cadena de la cabecera tiene una longitud imposible.", "A string in the header is implausibly long."],
  hint_gguf_string_long: ["El archivo no es un GGUF legible (v2 o v3).", "The file is not a readable GGUF (v2 or v3)."],
  err_gguf_value_type: ["Tipo de valor desconocido ({kind}) en la cabecera.", "Unknown value type {kind} in the header."],
  hint_gguf_value_type: ["El archivo no es un GGUF legible (v2 o v3).", "The file is not a readable GGUF (v2 or v3)."],
  err_gguf_magic: ["Los bytes iniciales no son de un GGUF.", "The magic bytes are not GGUF."],
  hint_gguf_magic: ["El archivo no es un GGUF legible (v2 o v3).", "The file is not a readable GGUF (v2 or v3)."],
  err_gguf_version: ["La versión {version} de GGUF no está admitida (sí la 2 y la 3).", "GGUF version {version} is not supported (2 and 3 are)."],
  hint_gguf_version: ["El archivo no es un GGUF legible (v2 o v3).", "The file is not a readable GGUF (v2 or v3)."],
  err_gguf_count: ["El número de pares clave/valor es imposible.", "The key/value count is implausible."],
  hint_gguf_count: ["El archivo no es un GGUF legible (v2 o v3).", "The file is not a readable GGUF (v2 or v3)."],
  err_file_unreadable: ["No se puede abrir {path}: {detail}.", "Cannot open {path}: {detail}."],
  err_repo_id_invalid: ["«{repo}» no es un identificador de repositorio de Hugging Face.", "'{repo}' is not a Hugging Face repository id."],
  hint_repo_id_invalid: ["Usa la forma organización/nombre, por ejemplo Qwen/Qwen3-4B.", "Use the form organisation/name, e.g. Qwen/Qwen3-4B."],
  err_offline_mode: ["La aplicación está en modo sin red.", "The app is running in offline mode."],
  hint_offline_mode: ["Quita PYGMALION_OFFLINE para buscar o descargar.", "Unset PYGMALION_OFFLINE to search or download."],
  err_hf_unreachable: ["No se puede contactar con Hugging Face: {detail}.", "Cannot reach Hugging Face: {detail}."],
  hint_hf_unreachable: ["Comprueba la conexión; los modelos locales siguen funcionando.", "Check the connection; local models still work."],
  err_hf_not_found: ["Ese repositorio no existe en Hugging Face (o es privado).", "That repository does not exist on Hugging Face (or it is private)."],
  hint_hf_not_found: ["Comprueba el identificador.", "Check the id."],
  err_hf_refused: ["Hugging Face rechazó la petición (repositorio restringido o privado).", "Hugging Face refused the request (gated or private repository)."],
  hint_hf_refused: ["Acepta la licencia en la web y guarda tu token en Ajustes.", "Accept the licence on the website and save your token in Settings."],
  err_hf_status: ["Hugging Face respondió {status}.", "Hugging Face answered {status}."],
  hint_hf_status: ["Inténtalo de nuevo más tarde.", "Try again later."],
  err_hf_unreadable: ["Hugging Face envió una respuesta ilegible.", "Hugging Face sent an unreadable answer."],
  err_hf_pipeline_unknown: ["Tarea desconocida: «{pipeline}».", "Unknown pipeline '{pipeline}'."],
  hint_hf_pipeline_unknown: ["Usa una de estas: {options}.", "Use one of: {options}."],
  err_hf_sort_unknown: ["Orden desconocido: «{sort}».", "Unknown sort '{sort}'."],
  hint_hf_sort_unknown: ["Usa uno de estos: {options}.", "Use one of: {options}."],
  err_quant_type_unknown: ["Tipo de cuantización desconocido: «{type}».", "Unknown quantization type '{type}'."],
  hint_quant_type_unknown: ["Disponibles: {options}.", "Offered: {options}."],
  err_quant_type_needed: ["Elige al menos un tipo de cuantización.", "Pick at least one quantization type."],
  hint_quant_type_needed: ["Disponibles: {options}.", "Offered: {options}."],
  err_outtype_unknown: ["Tipo de salida desconocido: «{outtype}».", "Unknown output type '{outtype}'."],
  hint_outtype_unknown: ["Usa uno de estos: {options}.", "Use one of: {options}."],
  err_calib_missing: ["Falta el texto de calibración incluido.", "The bundled calibration text is missing."],
  hint_calib_missing: ["Reinstala la aplicación o indica un dataset como origen de la calibración.", "Reinstall the app or pass a dataset as the calibration source."],
  err_not_model_folder: ["{folder} no es una carpeta de modelo de Hugging Face.", "{folder} is not a Hugging Face model folder."],
  hint_not_model_folder: ["Necesita un config.json y archivos .safetensors.", "It needs a config.json and .safetensors files."],
  err_artifact_ref_needed: ["Hace falta el identificador, el nombre o la ruta de un artefacto.", "An artifact id, name or path is needed."],
  err_artifact_wrong_kind: ["{name} es de tipo «{kind}», y hace falta uno de estos: {options}.", "{name} is a {kind}, not one of: {options}."],
  hint_artifact_wrong_kind: ["Elige un artefacto del tipo adecuado en la tabla de linaje.", "Pick an artifact of the right kind in the lineage table."],
  err_name_empty: ["El nombre no puede estar vacío.", "The name cannot be empty."],
  err_artifact_published: ["{name} está publicado ({where}).", "{name} is published ({where})."],
  hint_artifact_published: ["Retira antes la publicación.", "Unpublish it first."],
  err_files_outside_work: ["{path} está fuera de la carpeta de trabajo: sus archivos no se borran.", "{path} is outside the work folder: its files are not deleted."],
  hint_files_outside_work: ["Bórralos a mano si estás seguro.", "Delete them by hand if you are sure."],
  err_delete_failed: ["No se puede borrar {path}: {detail}", "Cannot delete {path}: {detail}"],
  hint_delete_failed: ["Cierra lo que lo esté usando e inténtalo de nuevo.", "Close whatever uses it and try again."],
  // ---- datasets
  err_dataset_file_missing: ["Falta el archivo de la versión {n}: {path}.", "The file of version {n} is missing: {path}."],
  hint_dataset_file_missing: ["Restaura data/datasets o reconstruye el dataset.", "Restore data/datasets or rebuild the dataset."],
  err_source_needed: ["Un dataset necesita al menos un origen.", "A dataset needs at least one source."],
  hint_source_needed: ["Añade archivos, una carpeta, JSONL, CSV, una app de la familia o un origen sintético.", "Add files, a folder, JSONL, CSV, a family app or a synthetic source."],
  err_dataset_kind_unknown: ["Tipo de dataset desconocido: {kind}.", "Unknown dataset kind {kind}."],
  hint_dataset_kind_unknown: ["Tipos: {options}.", "Kinds: {options}."],
  err_no_usable_records: ["Ningún registro utilizable salió de los orígenes.", "No usable records came out of the sources."],
  hint_no_usable_records: ["Comprueba el formato de la entrada.", "Check the format of the input."],
  err_no_usable_records_notes: ["Ningún registro utilizable salió de los orígenes: {note}", "No usable records came out of the sources: {note}"],
  hint_no_usable_records_notes: ["Comprueba el formato de la entrada.", "Check the format of the input."],
  err_ops_removed_all: ["Las operaciones eliminaron todos los registros.", "The operations removed every record."],
  hint_ops_removed_all: ["Suaviza los filtros.", "Loosen the filters."],
  err_dataset_kind_mismatch: ["El dataset {name} contiene registros de tipo «{have}», no «{kind}».", "Dataset {name} holds {have} records, not {kind}."],
  hint_dataset_kind_mismatch: ["Crea un dataset nuevo para el otro tipo.", "Create a new dataset for the other kind."],
  err_dataset_name_needed: ["Un dataset nuevo necesita un nombre (letras, cifras, espacios, puntos y guiones).", "A new dataset needs a `name` (letters, digits, spaces, dots and hyphens)."],
  hint_dataset_name_needed: ["O indica un dataset existente para añadirle una versión.", "Or pass `dataset` to add a version to an existing one."],
  err_record_out_of_range: ["{label}: el registro {index} está fuera de rango (de 0 a {last}).", "{label}: record index {index} is out of range (0 to {last})."],
  err_record_edit_invalid: ["El registro editado {index} no es un dato válido de tipo «{kind}».", "The edited record {index} is not valid {kind} data."],
  err_file_forbidden: ["No se puede leer {path}: {reason}.", "Cannot read {path}: {reason}."],
  hint_file_forbidden: ["Elige un archivo de tus propias carpetas.", "Pick a file in your own folders."],
  err_file_too_big: ["{name} pesa más de {mb} MB.", "{name} is larger than {mb} MB."],
  hint_file_too_big: ["Divídelo antes.", "Split it first."],
  err_pasted_too_large: ["El texto pegado es demasiado grande.", "The pasted text is too large."],
  hint_pasted_too_large: ["Guárdalo en un archivo y usa su ruta.", "Save it to a file and use its path."],
  err_source_text_or_path: ["El origen «{type}» necesita un texto o una ruta.", "The {type} source needs `text` or `path`."],
  err_csv_columns_needed: ["Un origen CSV necesita indicar las columnas, por ejemplo {{\"prompt\": \"pregunta\", \"response\": \"respuesta\"}} o {{\"text\": \"texto\"}}.", "A CSV source needs `columns`, e.g. {{\"prompt\": \"pregunta\", \"response\": \"respuesta\"}} or {{\"text\": \"texto\"}}."],
  err_csv_column_missing: ["El CSV no tiene la columna {missing}.", "The CSV has no column {missing}."],
  hint_csv_column_missing: ["Sus columnas son: {columns}.", "Its columns are: {columns}."],
  err_files_source_needs: ["Un origen de archivos necesita textos con nombre o rutas.", "A files source needs `items` (name and text) or `paths`."],
  err_folder_forbidden: ["No se puede leer {path}: {reason}.", "Cannot read {path}: {reason}."],
  hint_folder_forbidden: ["Elige una carpeta dentro de tus documentos.", "Pick a folder inside your own documents."],
  err_family_offline: ["El hub de la familia no está disponible.", "The family hub is not available."],
  hint_family_offline: ["Arranca Hoard Hub o usa otro origen.", "Start Hoard Hub, or use another source."],
  err_family_source_needs: ["Un origen de la familia necesita una app y una herramienta.", "A family source needs `app` and `tool`."],
  err_family_no_answer: ["{app}.{tool} no respondió: {why}.", "{app}.{tool} did not answer: {why}."],
  hint_family_no_answer: ["Comprueba que la app está en marcha y que el nombre de la herramienta es correcto.", "Check that the app is running and the tool name is right."],
  err_family_mapping_needed: ["Un origen de la familia necesita indicar la correspondencia de campos, por ejemplo {{\"prompt\": \"front\", \"response\": \"back\"}}.", "A family source needs `mapping`, e.g. {{\"prompt\": \"front\", \"response\": \"back\"}}."],
  err_teacher_missing: ["No hay ningún modelo profesor disponible.", "No teacher model is available."],
  hint_teacher_missing: ["Arranca un servidor de modelos (Faustus, llama.cpp u Ollama) o indica teacher.model.", "Start a model server (Faustus, llama.cpp or Ollama) or set teacher.model."],
  err_synthetic_task_needed: ["Un origen sintético necesita una tarea, por ejemplo «genera 3 preguntas y respuestas sobre este fragmento».", "A synthetic source needs a `task`, e.g. \"genera 3 preguntas y respuestas sobre este fragmento\"."],
  err_source_type_unknown: ["Tipo de origen desconocido: {type}.", "Unknown source type {type}."],
  hint_source_type_unknown: ["Usa uno de estos: {options}.", "Use one of: {options}."],
  err_unknown_secret: ["Secreto desconocido: {name}.", "Unknown secret {name}."],
  hint_unknown_secret: ["Disponibles: {options}.", "Known: {options}."],
  err_confirm_permanent: ["{what} es permanente.", "{what} is permanent."],
  hint_confirm_permanent: ["Repite la llamada con confirm=true si el usuario lo ha pedido.", "Repeat the call with confirm=true if the user asked for it."],
  err_convert_target_needed: ["Indica un modelo (de Hugging Face) o un adaptador LoRA.", "Give model (a Hugging Face model) or adapter (a LoRA adapter)."],
  err_env_python_unset: ["env.python no está indicado.", "env.python is not set."],
  hint_env_python_unset: ["Crea el entorno del entrenador e indica env.python en Ajustes.", "Create the trainer environment and set env.python in Settings."],
  err_env_python_missing: ["{python} no existe.", "{python} does not exist."],
  hint_env_python_missing: ["Comprueba env.python en Ajustes.", "Check env.python in Settings."],
  err_work_unwritable: ["No se puede escribir en la carpeta de trabajo: {detail}", "Cannot write in the work folder: {detail}"],
  hint_work_unwritable: ["Comprueba paths.work en Ajustes.", "Check paths.work in Settings."],
  err_probe_failed: ["La comprobación falló: {detail}", "The probe failed: {detail}"],
  hint_probe_failed: ["Ejecuta el intérprete a mano para ver el motivo.", "Run the interpreter by hand to see why."],
  err_probe_silent: ["La comprobación no imprimió nada.", "The probe printed nothing."],
  hint_probe_silent: ["Ejecuta el intérprete a mano para ver el motivo.", "Run the interpreter by hand to see why."],
  // ---- workers
  err_args_unreadable: ["No se puede leer el archivo de argumentos {path}: {detail}", "Cannot read the arguments file {path}: {detail}"],
  err_module_unloadable: ["No se puede cargar {path}.", "Cannot load {path}."],
  err_ctx_factor_low: ["El factor debe ser mayor que 1.", "The factor must be above 1."],
  hint_ctx_factor_low: ["Usa 2, 4 u 8.", "Use 2, 4 or 8."],
  err_ctx_no_max_position: ["La configuración del modelo no tiene max_position_embeddings.", "The model's config has no max_position_embeddings."],
  hint_ctx_no_max_position: ["Indica original_max_position.", "Pass original_max_position explicitly."],
  err_hf_read_failed: ["No se puede leer {repo} en Hugging Face: {detail}", "Cannot read {repo} on Hugging Face: {detail}"],
  hint_hf_read_failed: ["Comprueba el identificador del repositorio y tu conexión.", "Check the repository id and your connection."],
  err_download_stopped: ["Detenido a petición; vuelve a iniciar la descarga para reanudarla.", "Stopped by request; start the download again to resume."],
  err_download_failed: ["La descarga falló: {detail}", "Download failed: {detail}"],
  hint_download_failed: ["Ejecútala de nuevo: la descarga se reanuda.", "Run it again: the download resumes."],
  err_download_no_config: ["La descarga terminó sin config.json.", "The download finished without a config.json."],
  hint_download_no_config: ["Puede que el repositorio no sea un modelo de transformers.", "The repository may not be a transformers model."],
  err_adapter_config_unreadable: ["{path}: falta adapter_config.json o no se puede leer.", "{path}: adapter_config.json is missing or unreadable."],
  hint_adapter_config_unreadable: ["Elige la carpeta del adaptador escrita por un entrenamiento.", "Pick the adapter folder written by a training job."],
  err_merge_stopped: ["Detenido a petición; vuelve a iniciar la fusión (no se conserva nada a medias).", "Stopped by request; start the merge again (nothing partial is kept)."],
  err_adapter_shape_misfit: ["{name}: las formas del adaptador {lora_b} x {lora_a} no encajan con el peso base {weight}.", "{name}: the adapter shapes {lora_b} x {lora_a} do not fit the base weight {weight}."],
  hint_adapter_shape_misfit: ["El adaptador se entrenó sobre otro modelo base.", "The adapter was trained on a different base model."],
  err_merge_cuda_missing: ["Se pidió CUDA para la fusión pero no está disponible.", "CUDA was requested for the merge but is not available."],
  hint_merge_cuda_missing: ["Usa device=cpu.", "Use device=cpu."],
  err_merge_base_invalid: ["{path}: no es una carpeta de modelo de Hugging Face (falta config.json).", "{path}: not a Hugging Face model folder (config.json missing)."],
  err_adapter_weights_missing: ["{path}: no se encuentra adapter_model.safetensors.", "{path}: adapter_model.safetensors not found."],
  hint_adapter_weights_missing: ["Solo se fusionan adaptadores safetensors; un adapter_model.bin basado en pickle se rechaza.", "Only safetensors adapters are merged; a pickle-based adapter_model.bin is refused."],
  err_adapter_not_streamable: ["Este adaptador no se puede fusionar en flujo.", "This adapter cannot be merged by streaming."],
  hint_adapter_not_streamable: ["Usa mode=auto o transformers.", "Use mode=auto or transformers."],
  err_merge_method_unknown: ["Método de fusión desconocido: {method}.", "Unknown merge method {method}."],
  hint_merge_method_unknown: ["Usa uno de estos: {options}.", "Use one of: {options}."],
  err_merge_slerp_two: ["slerp fusiona exactamente dos modelos.", "slerp merges exactly two models."],
  hint_merge_slerp_two: ["Elige dos modelos o usa linear.", "Pick two models or use linear."],
  err_merge_needs_base: ["{method} necesita un modelo base.", "{method} needs a base model."],
  hint_merge_needs_base: ["Elige el modelo del que partieron los demás.", "Pick the model the others were tuned from."],
  err_merge_needs_two: ["Una fusión necesita al menos dos modelos.", "A merge needs at least two models."],
  err_train_no_cuda: ["El entrenador no ve ninguna GPU CUDA.", "No CUDA device is visible to the trainer."],
  hint_train_no_cuda: ["Ejecuta la comprobación del entorno; el trabajo necesita una GPU permitida con PyTorch funcionando.", "Run env_check; the job needs an allowed GPU with a working PyTorch build."],
  err_bnb_missing: ["bitsandbytes no está instalado en el entorno del entrenador.", "bitsandbytes is not installed in the trainer environment."],
  hint_bnb_missing: ["Ejecuta pip install bitsandbytes (una versión con CUDA).", "pip install bitsandbytes (a CUDA build)."],
  err_no_target_layers: ["Ninguna capa lineal coincide con los módulos pedidos.", "No linear layers matched the requested target modules."],
  hint_no_target_layers: ["Usa target_modules=['all'] o nombres como q_proj, v_proj.", "Use target_modules=['all'] or names such as q_proj, v_proj."],
  err_no_label_tokens: ["La parte de entrenamiento no produjo ningún ejemplo con tokens etiquetados.", "The training split produced no example with labelled tokens."],
  hint_no_label_tokens: ["Comprueba el formato del dataset y que la plantilla de chat acepta sus roles.", "Check the dataset format and that the chat template accepts its roles."],
  // ---- extra
  err_unknown_tool: ["Herramienta desconocida: {name}", "Unknown tool: {name}"],
  // ---- jobs (texts)
  msg_job_cancelled_early: ["Cancelado antes de empezar.", "Cancelled before it started."],
  msg_job_lost: ["El trabajo se detuvo sin avisar; reanúdalo para continuar.", "The job stopped without reporting; resume it to continue."],
  msg_next_step_failed: ["El siguiente paso de la cadena no pudo empezar: {reason}", "The next pipeline step could not start: {reason}"],
  // ---- ops (texts)
  msg_download_confirm: ["Repite con confirm=true para descargar {gb} GB en {folder}.", "Repeat with confirm=true to download {gb} GB into {folder}."],
  msg_title_download: ["descargar {name}", "download {name}"],
  msg_title_dataset: ["dataset {name}", "dataset {name}"],
  msg_title_train: ["entrenar", "train"],
  msg_title_merge: ["fusionar", "merge"],
  msg_title_merge_models: ["fusionar modelos", "merge models"],
  msg_title_ctx_extend: ["ampliar contexto", "extend context"],
  msg_title_convert_adapter: ["convertir adaptador", "convert adapter"],
  msg_title_convert: ["convertir", "convert"],
  msg_title_perplexity: ["perplejidad {name}", "perplexity {name}"],
  msg_title_evaluate: ["evaluar {name}", "evaluate {name}"],
  msg_title_publish: ["publicar {name}", "publish {name}"],
  msg_ctx_fit_note: ["Caché KV en f16; suma el tamaño del archivo y 600 MB de margen. Cuantizar la caché (q8_0) reduce a la mitad la columna KV.", "KV cache in f16; add the file size and 600 MB headroom. Cache quantization (q8_0) halves the KV column."],
  // ---- vram (texts)
  msg_mem_formula_qlora: ["pesos ({params_b}B - {kept_b}B de embeddings) x {q_bytes} B + {kept_b}B x {l_bytes} B = {weights_mb} MB; LoRA {lora_m}M x {state_bytes} B = {lora_mb} MB; puntos de control {batch}x{seq_len}x{hidden}x{layers}x2x{k} B = {checkpoints_mb} MB; memoria de trabajo {working_mb} MB; logits {batch}x{seq_len}x{vocab}x4x2 B = {logits_mb} MB; sobrecarga {fixed_mb} MB + {pct} % = {overhead_mb} MB", "weights ({params_b}B - {kept_b}B embeddings) x {q_bytes} B + {kept_b}B x {l_bytes} B = {weights_mb} MB; LoRA {lora_m}M x {state_bytes} B = {lora_mb} MB; checkpoints {batch}x{seq_len}x{hidden}x{layers}x2x{k} B = {checkpoints_mb} MB; working set {working_mb} MB; logits {batch}x{seq_len}x{vocab}x4x2 B = {logits_mb} MB; overhead {fixed_mb} MB + {pct} % = {overhead_mb} MB"],
  msg_mem_formula_lora: ["pesos {params_b}B x {l_bytes} B = {weights_mb} MB; LoRA {lora_m}M x {state_bytes} B = {lora_mb} MB; puntos de control {batch}x{seq_len}x{hidden}x{layers}x2x{k} B = {checkpoints_mb} MB; memoria de trabajo {working_mb} MB; logits {batch}x{seq_len}x{vocab}x4x2 B = {logits_mb} MB; sobrecarga {fixed_mb} MB + {pct} % = {overhead_mb} MB", "weights {params_b}B x {l_bytes} B = {weights_mb} MB; LoRA {lora_m}M x {state_bytes} B = {lora_mb} MB; checkpoints {batch}x{seq_len}x{hidden}x{layers}x2x{k} B = {checkpoints_mb} MB; working set {working_mb} MB; logits {batch}x{seq_len}x{vocab}x4x2 B = {logits_mb} MB; overhead {fixed_mb} MB + {pct} % = {overhead_mb} MB"],
  msg_pick_no_inventory: ["No hay inventario de GPU (no se encuentra nvidia-smi).", "No GPU inventory (nvidia-smi not found)."],
  msg_pick_no_fit: ["{total_mb} MB no caben en las GPU permitidas juntas ({capacity_mb} MB).", "{total_mb} MB do not fit in the allowed GPUs together ({capacity_mb} MB)."],
  msg_time_note: ["Estimación aproximada a partir de una velocidad de referencia; cuando el trabajo arranca, la velocidad medida y el tiempo restante real la sustituyen.", "Rough estimate from a throughput constant; once the job runs, the measured speed and the real ETA replace it."],
  msg_time_formula: ["arranque {startup_s} s + {tokens} tokens x {padding} (relleno) / {tok_s} tokens/s + {steps} pasos x {step_s} s. Velocidad = {const} / {params_b}B parámetros x {scale} (tarjeta) x {speed} ({method}), como máximo {cap} tokens/s.", "start-up {startup_s} s + {tokens} tokens x {padding} (padding) / {tok_s} tokens/s + {steps} steps x {step_s} s. Throughput = {const} / {params_b}B params x {scale} (card) x {speed} ({method}), at most {cap} tokens/s."],
  // ---- gpus (texts)
  msg_gpu_status_none: ["No se ha encontrado ninguna GPU NVIDIA (nvidia-smi no está disponible).", "No NVIDIA GPU was found (nvidia-smi is not available)."],
  msg_gpu_plan_wait: ["La estimación ({total_mb} MB) supera la memoria libre de todas las GPU permitidas ahora mismo; el trabajo esperará a que el hub de la familia libere una.", "The estimate ({total_mb} MB) is more than the free memory of every allowed GPU right now; the job will wait for the family hub to free one."],
  msg_gpu_plan_no_fit: ["La estimación ({total_mb} MB) no cabe en las GPU permitidas.", "The estimate ({total_mb} MB) does not fit in the allowed GPUs."],
  msg_gpu_plan_no_inventory: ["No hay inventario de GPU: la estimación no se puede comparar con la memoria libre.", "No GPU inventory: the estimate cannot be compared with the free memory."],
  // ---- planner (texts)
  msg_plan_seq_lowered: ["Se ha bajado seq_len a {seq_len} para que el entrenamiento quepa en {mb} MB.", "seq_len lowered to {seq_len} so the run fits {mb} MB."],
  msg_plan_lora_big: ["LoRA normal mantiene el modelo en bf16 y no cabe en las GPU permitidas; QLoRA necesita aproximadamente la cuarta parte de la memoria.", "Plain LoRA keeps the model in bf16 and does not fit the allowed GPUs; QLoRA needs about a quarter of the memory."],
  msg_plan_few_steps: ["Menos de 20 pasos del optimizador: el adaptador apenas cambiará el modelo. Añade datos o baja grad_accum.", "Fewer than 20 optimizer steps: the adapter will hardly change the model. Add data or lower grad_accum."],
  msg_plan_few_records: ["Solo hay {n} registros de entrenamiento: es probable que sobreajuste; con 200 o más se empieza con más seguridad.", "Only {n} training records: expect overfitting; 200 or more is a safer start."],
  msg_plan_no_inventory: ["No hay inventario de GPU: no se encuentra nvidia-smi, así que no se puede comprobar si cabe.", "No GPU inventory: nvidia-smi was not found, so the fit cannot be checked."],
  msg_plan_no_fit: ["La estimación no cabe en las GPU permitidas.", "The estimate does not fit the allowed GPUs."],
  msg_plan_wait_free: ["La estimación no cabe en la memoria libre de ninguna GPU permitida ahora mismo; el trabajo esperará a que el hub libere una.", "The estimate does not fit the free memory of any allowed GPU right now; the job will wait for the hub to free one."],
  msg_title_imatrix: ["matriz de importancia", "importance matrix"],
  msg_title_quantize: ["cuantizar {type}", "quantize {type}"],
  msg_title_perplexity_step: ["perplejidad", "perplexity"],
  msg_title_perplexity_of: ["perplejidad ({what})", "perplexity ({what})"],
  msg_title_baseline_perplexity: ["base: perplejidad ({what})", "baseline: perplexity ({what})"],
  msg_title_publish_step: ["publicar", "publish"],
  msg_title_evaluate_step: ["evaluar", "evaluate"],
  msg_title_baseline_convert: ["referencia: convertir", "baseline: convert"],
  msg_title_baseline_imatrix: ["referencia: matriz de importancia", "baseline: importance matrix"],
  msg_title_baseline_quantize: ["referencia: cuantizar {type}", "baseline: quantize {type}"],
  // ---- publish (texts)
  msg_publish_note_rope: ["El GGUF lleva escalado rope {type} (factor {factor}); Ollama lo lee del archivo.", "The GGUF carries {type} rope scaling (factor {factor}); Ollama reads it from the file."],
  msg_publish_note_no_template: ["El GGUF no tiene plantilla de chat: indica template= o Ollama usará un prompt simple.", "The GGUF has no chat template: pass template= or Ollama will use a plain prompt."],
  msg_publish_note_llama: ["Añadido a los servicios del hub. Arráncalo desde el hub; Pygmalion no lo arranca.", "Added to the hub's backends. Start it from the hub; Pygmalion does not start it."],
  msg_note_unpublished: ["Publicación retirada.", "Unpublished."],
  // ---- runners (texts)
  msg_what_merged_model: ["el modelo fusionado", "the merged model"],
  msg_what_gguf_file: ["el archivo GGUF", "the GGUF file"],
  msg_what_quantized_file: ["el archivo cuantizado", "the quantized file"],
  msg_progress_training: ["entrenando", "training"],
  msg_progress_convert_adapter: ["convirtiendo el adaptador LoRA a GGUF ({outtype})", "converting the LoRA adapter to GGUF ({outtype})"],
  msg_progress_convert_model: ["convirtiendo el modelo a GGUF ({outtype})", "converting the model to GGUF ({outtype})"],
  msg_progress_imatrix: ["calculando la matriz de importancia", "computing the importance matrix"],
  msg_progress_quantize: ["cuantizando a {type}", "quantizing to {type}"],
  msg_progress_perplexity: ["midiendo la perplejidad", "measuring perplexity"],
  msg_publish_note_ctx_above: ["num_ctx {ctx} supera el contexto con el que se entrenó el modelo ({trained}).", "num_ctx {ctx} is above the context the model was trained for ({trained})."],
  msg_progress_eval_suite: ["preparando en Galton la suite con los registros reservados", "preparing the suite of held-out records in Galton"],
  msg_eval_suite_reused: ["Se reutiliza la suite {name} de Galton ({n} casos).", "Reusing Galton's suite {name} ({n} cases)."],
  msg_eval_suite_created: ["Se creó la suite {name} en Galton con {n} casos de los registros reservados.", "Built Galton's suite {name} with {n} cases from the held-out records."],
  msg_eval_records_capped: ["Solo se usaron {n} de los {total} registros reservados (ajuste galton.eval_cases).", "Only {n} of the {total} held-out records were used (setting galton.eval_cases)."],
  msg_eval_ref_explicit: ["Se compara con {model}, como se pidió.", "Compared with {model}, as asked."],
  msg_eval_ref_parent: ["Se compara con su archivo padre {model}: la diferencia que se mide es el formato del archivo, no un entrenamiento.", "Compared with its parent {model}: the difference measured is the file format, not a training."],
  msg_eval_ref_base: ["Se compara con el modelo base {model} en {quant}.", "Compared with the base model {model} at {quant}."],
  msg_eval_ref_base_build: ["Se compara con el modelo base {model} en {quant} (se preparará antes, porque aún no existe).", "Compared with the base model {model} at {quant} (it will be prepared first, as it does not exist yet)."],
  msg_eval_ref_context: ["Se compara con {model} sin la extensión de contexto, en {quant}.", "Compared with {model} without the context extension, at {quant}."],
  msg_eval_ref_context_build: ["Se compara con {model} sin la extensión de contexto, en {quant} (se preparará antes, porque aún no existe).", "Compared with {model} without the context extension, at {quant} (it will be prepared first, as it does not exist yet)."],
  msg_eval_ref_imatrix: ["La referencia usa una matriz de importancia calculada con el mismo texto de calibración que el resultado.", "The reference uses an importance matrix computed on the same calibration text as the result."],
  msg_eval_ref_unknown_base: ["El modelo con el que se entrenó este resultado no está en el linaje, así que se compara con su archivo padre, que mide más la cuantización que el entrenamiento.", "The model this result was trained from is not in the lineage, so it is compared with its parent file, which measures the quantization more than the training."],
  msg_eval_pending_judge: ["A {n} respuestas aún les falta la calificación del juez; el veredicto se apoya en las demás.", "{n} answers still wait for the judge; the verdict rests on the others."],
  msg_progress_galton: ["Ejecución {run} de Galton: {state}", "Galton run {run}: {state}"],
  msg_note_rope_missing: ["El conversor no escribió escalado rope en el GGUF; ejecútalo con --rope-scaling yarn --rope-scale N --yarn-orig-ctx M (mira extra_args de publish_llama).", "The converter wrote no rope scaling into the GGUF; run it with --rope-scaling yarn --rope-scale N --yarn-orig-ctx M (see publish_llama extra_args)."],
  // ---- misc (texts)
  msg_quant_needs_imatrix: ["{type} sin matriz de importancia da malos resultados; activa la matriz.", "{type} without an importance matrix gives poor results; turn the matrix on."],
  msg_convert_note_no_script: ["No se encuentra convert_hf_to_gguf.py; indica llama.src_dir en Ajustes.", "convert_hf_to_gguf.py was not found; set llama.src_dir in Settings."],
  msg_convert_note_no_arches: ["El script de conversión no lista arquitecturas (versión desconocida).", "The conversion script lists no architectures (unknown version)."],
  msg_convert_note_no_arch: ["El config.json del modelo no nombra ninguna arquitectura.", "The model's config.json names no architecture."],
  msg_convert_note_unregistered: ["{arch} no está registrada en esta versión del script de conversión; actualiza llama.cpp.", "{arch} is not registered in this version of the conversion script; update llama.cpp."],
  // ---- datasets (texts)
  msg_note_bad_lines: ["{label}: {bad} líneas no eran objetos JSON válidos y se omitieron.", "{label}: {bad} lines were not valid JSON objects and were skipped."],
  msg_note_folder_many: ["La carpeta tiene más de {max} archivos; el resto no se leyó.", "The folder has more than {max} files; the rest were not read."],
  msg_note_file_big: ["{name} pesa más de {mb} MB y se omitió.", "{name} is larger than {mb} MB and was skipped."],
  msg_note_items_unmapped: ["{label}: {skipped} elementos no tenían un campo indicado y se omitieron.", "{label}: {skipped} items lacked a mapped field and were skipped."],
  msg_note_teacher_failed: ["El modelo profesor falló en el fragmento {chunk}: {detail}", "The teacher failed on chunk {chunk}: {detail}"],
  msg_synthetic_note: ["Estimación: unos 25 s por llamada con un modelo de 27B; la primera llamada muestra la velocidad real.", "Estimate: about 25 s per call with a 27B model; the first call shows the real speed."],
  msg_progress_source: ["origen {n}/{total}: {type}", "source {n}/{total}: {type}"],
  msg_progress_synthetic: ["sintético {n}/{total}", "synthetic {n}/{total}"],
  msg_path_invalid: ["no es una ruta válida", "not a valid path"],
  msg_path_relative: ["la ruta debe ser absoluta", "the path must be absolute"],
  msg_path_unresolved: ["no se puede resolver la ruta", "the path cannot be resolved"],
  msg_folder_missing: ["la carpeta no existe", "the folder does not exist"],
  msg_path_root: ["la raíz de una unidad es demasiado amplia", "a drive root is too broad"],
  msg_path_home: ["la carpeta del perfil de usuario es demasiado amplia: elige una subcarpeta", "the user profile folder is too broad: pick a subfolder"],
  msg_path_system: ["no se permiten las carpetas del sistema", "system folders are not allowed"],
  msg_path_own_data_folder: ["no se puede leer la carpeta de datos de la propia aplicación", "the app's own data folder cannot be read"],
  msg_path_own_data_file: ["la carpeta de datos de la propia aplicación está vedada", "the app's own data folder is off limits"],
  msg_path_hidden: ["no se permiten las carpetas de configuración ni las ocultas", "configuration and hidden folders are not allowed"],
  msg_file_missing: ["el archivo no existe", "the file does not exist"],
  msg_path_credentials: ["parece un archivo de credenciales", "that looks like a credentials file"],
  msg_detail_offline: ["sin red", "offline"],
  msg_env_trainer: ["entorno del entrenador", "trainer environment"],
  msg_env_not_found: ["no se encuentra", "not found"],
  msg_env_not_in_src: ["no se encuentra en llama.src_dir", "not found in llama.src_dir"],
  msg_env_ollama_missing: ["no se encuentra (solo hace falta para publicar en Ollama)", "not found (only needed to publish to Ollama)"],
  msg_env_unavailable: ["no disponible", "unavailable"],
  msg_env_lib_missing: ["falta", "missing"],
  msg_env_lib_old: ["la versión {version} es anterior a la {minimum}", "version {version} is older than {minimum}"],
  msg_env_no_cuda: ["no se ve ninguna GPU CUDA (versión solo CPU o sin controlador)", "no CUDA device is visible (CPU-only build, or no driver)"],
  msg_env_fix_llama_bin: ["Descarga una versión de llama.cpp para tu GPU e indica su carpeta en llama.bin_dir.", "Download a llama.cpp release for your GPU and set llama.bin_dir to its folder."],
  msg_env_fix_ollama: ["Instala Ollama desde su web o indica publish.ollama_exe.", "Install Ollama from its website, or set publish.ollama_exe."],
  // ---- workers (texts)
  msg_tip_oom: ["La GPU se quedó sin memoria. Baja el tamaño de lote o la longitud de secuencia, usa QLoRA o libera la GPU.", "The GPU ran out of memory. Lower the batch size or the sequence length, use QLoRA, or free the GPU."],
  msg_tip_module: ["Instálalo en el entorno del entrenador: pip install {module}.", "Install it in the trainer environment: pip install {module}."],
  msg_tip_gated: ["Este repositorio es restringido: acepta su licencia en Hugging Face y guarda tu token en Ajustes.", "This repository is gated: accept its licence on Hugging Face and save your token in Settings."],
  msg_tip_disk: ["El disco está lleno: libera espacio en la carpeta de trabajo.", "The disk is full: free space in the work folder."],
  msg_tip_cuda: ["El entorno del entrenador no tiene una versión de PyTorch con CUDA que funcione. Ejecuta la comprobación del entorno para ver el comando de instalación.", "The trainer environment has no working CUDA build of PyTorch. Run env_check for the install command."],
  msg_tip_arch: ["Esta versión de transformers no puede cargar esa arquitectura. Actualiza transformers en el entorno del entrenador.", "This transformers version cannot load that architecture. Update transformers in the trainer environment."],
  // ---- extra (texts)
  msg_merge_problem_lacks: ["al modelo {idx} le faltan {n} tensores del primero (por ejemplo {name})", "model {idx} lacks {n} tensors of the first (e.g. {name})"],
  msg_merge_problem_extra: ["el modelo {idx} tiene {n} tensores que el primero no tiene (por ejemplo {name})", "model {idx} has {n} tensors the first lacks (e.g. {name})"],
  msg_merge_problem_shape: ["{name}: forma {first} en el primero y {other} en el modelo {idx}", "{name}: shape {first} in the first, {other} in model {idx}"],
};
